Repository Kernel360/KDEV4-HouseHub-FE, pull requests merged in 2025-05, with the labels that each got.

#120 youngseok, feat: 고객 태그 매핑 구현 + 고객 목록 + 고객 상세 페이지 태그 정보 출력
  src/api/tag.ts
  src/components/customers/CustomerDetailModal.tsx
  src/components/customers/CustomerForm.tsx
  src/components/ui/DatePicker.tsx
  src/components/ui/Select.tsx
  src/pages/customers/CustomerDetailPage.tsx
  src/pages/customers/customer.tsx
  src/types/customer.ts
  src/types/tag.ts
Labels: Feature

#121 youngseok, 고객 수정 모달 너비 조정 + 고객 정보 새로고침 버튼 삭제
  .husky/_/commit-msg
  src/components/customers/ConsultationForm.tsx
  src/components/customers/CustomerForm.tsx
  src/components/tag/TagList.tsx
  src/components/tag/TagSelector.tsx
  src/components/ui/DatePicker.tsx
  src/pages/customers/CustomerDetailPage.tsx
  src/pages/customers/customer.tsx
Labels: Refactor

#127 youngseok, feat: 중개인 프로필 페이지 + 중개인 수정 모달 추가 #126
  src/App.tsx
  src/api/agent.ts
  src/pages/auth/MyPage.tsx
  src/pages/auth/ProfileForm.tsx
  src/types/agent.ts
Labels: Feature

#128 계약 만료 예정 조회 기능 구현 및 UI 컴포넌트 리팩토링 #124
  src/components/dashboard/ContractExpiryAccordion.tsx
  src/components/dashboard/ContractItem.tsx
  src/components/dashboard/ContractList.tsx
  src/components/dashboard/MonthTabs.tsx
  src/pages/contract/ContractEdit.tsx
  src/pages/dashboard/Dashboard.tsx
  src/types/contract.ts
Labels: Feature

#129 youngseok, fix: 태그 수정 + 등록 시 방 개수만 하나만 선택 가능하게 수정 #119
  src/components/tag/TagList.tsx
  src/components/tag/TagSelector.tsx
  src/pages/customers/customer.tsx
Labels: Refactor

#133 youngseok, feat: agent 수정 페이지에서 생일축하템플릿 설정 + favicon + title 수정 #126
  index.html
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/logo.svg
  src/api/customer.ts
  src/api/sms.ts
  src/components/sms/SmsDetailModal.tsx
  src/components/ui/Select.tsx
  src/pages/auth/MyPage.tsx
  src/pages/auth/ProfileForm.tsx
  src/pages/customers/CustomerDetailPage.tsx
  src/pages/sms/send.tsx
  src/pages/sms/sms.tsx
  src/pages/sms/templates/[id].tsx
  src/pages/sms/templates/create.tsx
  src/pages/sms/templates/templates.tsx
  src/types/agent.ts
Labels: Feature

#134 seongeun, refactor: 매물 및 계약 백엔드 dto 리팩토링에 따른 프론트 수정 + 대시보드 API 반영
  src/api/contract.ts
  src/api/customer.ts
  src/components/contract/CompletedContractsModal.tsx
  src/components/contract/ContractListItem.tsx
  src/components/customers/RecentCustomersModal.tsx
  src/components/dashboard/StatCard.tsx
  src/pages/contract/ContractDetail.tsx
  src/pages/contract/ContractEdit.tsx
  src/pages/contract/ContractList.tsx
  src/pages/contract/ContractRegistration.tsx
  src/pages/customers/CustomerDetailPage.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/property/PropertyDetail.tsx
  src/pages/property/PropertyEdit.tsx
  src/pages/property/PropertyRegistration.tsx
  src/types/contract.ts
  src/types/customer.ts
  src/types/property.ts
Labels: Feature, Refactor

#136 byungchan, fix: 데이터 정합성 문제 해결 및 알림 상태 변경 시 UI 즉시 반영되지 않던 문제 해결 #135
  src/components/notification/NotificationItem.tsx
  src/context/NotificationContext.tsx
  src/pages/notification/NotificationPage.tsx
Labels: Bug

#146 공개 매물 페이지 중복 코드 제거 및 컴포넌트화, 메서드 추출 #145
  src/components/crawling-property/CrawlingPropertyCard.tsx
  src/components/crawling-property/PropertyCard.tsx
  src/components/crawling-property/PropertyDetailContent.tsx
  src/components/ui/PriceRangeInput.tsx
  src/components/ui/ToggleButtonGroup.tsx
  src/pages/crawling-property/CrawlingPropertyPage.tsx
Labels: Feature

#149 youngseok, 고객 상세에 공개 매물 중 추천 매물 탭 추가
  src/api/customer.ts
  src/components/crawling-property/CrawlingPropertyModal.tsx
  src/components/property/PropertyListItem.tsx
  src/pages/auth/MyPage.tsx
  src/pages/customers/CustomerDetailPage.tsx
  src/types/inquiry.ts
  src/types/property.ts
Labels: Feature

#150 seongeun, fix: 계약 등록 및 수정 시 고객 선택 로직 수정
  src/components/property/PropertySelectionModal.tsx
  src/pages/contract/ContractEdit.tsx
  src/pages/contract/ContractRegistration.tsx
Labels: Bug

#152 feature: 비밀번호 찾기 및 비밀번호 재설정 페이지 구현 및 API 연동
  src/App.tsx
  src/api/auth.ts
  src/pages/auth/ForgetPassword.tsx
  src/pages/auth/ResetPassword.tsx
  src/pages/auth/SignIn.tsx
  src/types/auth.ts
Labels: Feature

#154 youngseok, 크롤링 매물 추천에 태그 추가되게 수정 + mms 선택지 제거
  src/api/crawling-property.ts
  src/api/customer.ts
  src/components/crawling-property/CrawlingPropertyCard.tsx
  src/components/crawling-property/CrawlingPropertyDetailModal.tsx
  src/components/crawling-property/CrawlingPropertyList.tsx
  src/components/crawling-property/CrawlingPropertyModal.tsx
  src/components/crawling-property/PropertyCard.tsx
  src/components/crawling-property/PropertyDetailContent.tsx
  src/pages/crawling-property/CrawlingPropertyPage.tsx
  src/pages/customers/CustomerDetailPage.tsx
  src/pages/sms/send.tsx
  src/types/crawling-property.ts
  src/types/property.ts
  src/types/sms.ts
Labels: Bug

#155 SSE 연결 개선 - 중복 연결 방지 및 탭 가시성 대응
  src/App.tsx
  src/components/sse/SSEHandler.tsx
  src/components/sse/SSEManager.tsx
  src/context/NotificationContext.tsx
  src/hooks/useSSE.ts
  src/main.tsx
Labels: Refactor

#158 지역 선택 계층형 드롭다운 UI 구현 및 내 매물, 공개 매물 페이지에 적용
  src/App.tsx
  src/components/region/ThreeLevelSelect.tsx
  src/pages/crawling-property/CrawlingPropertyPage.tsx
  src/pages/property/PropertyList.tsx
  src/types/region.ts
Labels: Feature

#159 youngseok, fix: 고객 상세에 문자 예약일시를 형식화해서 표시 #147
  src/pages/customers/CustomerDetailPage.tsx
Labels: Refactor

#171 youngseok, fix: 대시보드 최근 고객 목록 페이지네이션 오류 수정 #170
  src/components/customers/RecentCustomersModal.tsx
Labels: Bug

#173 byungchan, fix: 알림 즉시 수신되지 않는 버그 해결 #172
  src/App.tsx
  src/api/notification.ts
  src/components/sse/SSEHandler.tsx
  src/components/sse/SSEManager.tsx
  src/context/NotificationContext.tsx
  src/hooks/useSSE.ts
Labels: Bug

#175 feature: 페이지 이동 시보다 매번 SSE 연결 시도하려고 하는 버그 해결 #174
  src/components/sse/SSEManager.tsx
  src/hooks/useSSE.ts
Labels: Bug

#176 byungchan, fix: sse 연결 url 변경 #174
  src/components/sse/SSEManager.tsx
Labels: Bug

#178 fix: 공개 매물 검색 시 필터 초기화 후 검색했는데 서울시 마포구 지정되는 버그 해결 #177
  src/pages/crawling-property/CrawlingPropertyPage.tsx
Labels: Bug
