Repository Kernel360/KDEV4-HouseHub-FE, pull requests merged in 2025-04, with the labels that each got.

#8 byungchan, feature: 회원가입 페이지 구현 및 API 연동
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/api/auth.ts
  src/api/client.ts
  src/components/Logo.tsx
  src/components/ToastContainer.tsx
  src/components/layout/AuthLayout.tsx
  src/components/ui/AddressInput.tsx
  src/components/ui/Button.stories.tsx
  src/components/ui/Input.tsx
  src/components/ui/Toast.tsx
  src/context/AuthContext.tsx
  src/context/ToastContext.tsx
  src/hooks/useEmailVerification.ts
  src/hooks/useToast.ts
  src/main.tsx
  src/pages/auth/SignUp.tsx
  src/types/auth.ts
  src/utils/validation.ts
  tailwind.config.js
  vitest.workspace.ts
Labels: Feature

#15 byungchan, feature: 로그인 페이지 및 대시보드 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/agent.ts
  src/api/auth.ts
  src/api/dashboard.ts
  src/components/LogoWithText.tsx
  src/components/dashboard/ActivityItem.tsx
  src/components/dashboard/ChartContainer.tsx
  src/components/dashboard/NotificationItem.tsx
  src/components/dashboard/StatCard.tsx
  src/components/layout/DashboardLayout.tsx
  src/components/ui/LoadingScreen.tsx
  src/context/AuthContext.tsx
  src/pages/auth/SignIn.tsx
  src/pages/dashboard/Dashboard.tsx
  src/types/agent.ts
  src/types/auth.ts
  src/types/dashboard.ts
  src/utils/validation.ts
Labels: Feature

#16 youngseok, feat: 고객 api 프론트 엔드 연결 + 고객 목록 페이지+모달들 구현 #13
  package-lock.json
  package.json
  src/App.tsx
  src/api/customer.ts
  src/components/ProtectedRoute.tsx
  src/components/customers/ConsultationForm.tsx
  src/components/customers/ConsultationList.tsx
  src/components/customers/CustomerDetailModal.tsx
  src/components/customers/CustomerForm.tsx
  src/components/customers/FilterPanel.tsx
  src/components/customers/PropertyRecommendations.tsx
  src/components/ui/Modal.tsx
  src/context/AuthContext.tsx
  src/pages/customers/[id].tsx
  src/pages/customers/customer.tsx
  src/types/consultation.ts
  src/types/customer.ts
  src/types/property.ts
  src/utils/format.ts
  tsconfig.app.json
Labels: Feature

#12 youngseok, chore: 허스키 적용 #11
  commitlint.config.mjs
  package-lock.json
  package.json
  postcss.config.js
  src/pages/customers/CustomerManagement.tsx
Labels: Chore

#19 [feat+ hotfix]: 고객 관리 페이지 관련 오류 해결 + 검색 이름/연락처/이메일로만 설정, husky 미적용 오류 해결 + commit-msg 깃헙에 업로드 #11
  .husky/_/applypatch-msg
  .husky/_/commit-msg
  .husky/_/h
  .husky/_/husky.sh
  .husky/_/post-applypatch
  .husky/_/post-checkout
  .husky/_/post-commit
  .husky/_/post-merge
  .husky/_/post-rewrite
  .husky/_/pre-applypatch
  .husky/_/pre-auto-gc
  .husky/_/pre-commit
  .husky/_/pre-merge-commit
  .husky/_/pre-push
  .husky/_/pre-rebase
  .husky/_/prepare-commit-msg
  package.json
  src/api/customer.ts
  src/components/customers/CustomerDetailModal.tsx
  src/pages/customers/customer.tsx
Labels: Bug, Feature

#25 byungchan, feature: 문의 템플릿 관리 페이지 구현 및 API 연동
  package-lock.json
  package.json
  src/App.tsx
  src/api/agent.ts
  src/api/auth.ts
  src/api/client.ts
  src/api/customer.ts
  src/api/dashboard.ts
  src/api/inquiryTemplate.ts
  src/components/ProtectedRoute.tsx
  src/components/inquiryTemplate/InquiryTemplateList.tsx
  src/components/inquiryTemplate/InquiryTemplatePreview.tsx
  src/components/inquiryTemplate/InquiryTemplatePreviewInfo.tsx
  src/components/inquiryTemplate/QuestionForm.tsx
  src/components/inquiryTemplate/QuestionItem.tsx
  src/components/inquiryTemplate/QuestionList.tsx
  src/components/inquiryTemplate/SortableItem.tsx
  src/components/layout/DashboardLayout.tsx
  src/components/ui/AddressInput.tsx
  src/components/ui/Checkbox.tsx
  src/components/ui/Toast.tsx
  src/context/AuthContext.tsx
  src/context/ToastContext.tsx
  src/context/useAuth.ts
  src/context/useToast.tsx
  src/hooks/useEmailVerification.ts
  src/hooks/useToast.ts
  src/main.tsx
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/inquiryTemplate/InquiryTemplateCreate.tsx
  src/pages/inquiryTemplate/InquiryTemplateManagement.tsx
  src/types/agent.ts
  src/types/api.ts
  src/types/auth.ts
  src/types/inquiryTemplate.ts
  src/utils/objectUtil.ts
Labels: Feature

#24 youngseok, hotfix: 빌드 실패와 관련된 customer 요소들 수정 #13 #22
  src/App.tsx
  src/api/customer.ts
  src/components/customers/ConsultationForm.tsx
  src/components/customers/CustomerDetailModal.tsx
  src/components/customers/CustomerForm.tsx
  src/components/inquiryTemplate/InquiryTemplatePreview.tsx
  src/components/layout/DashboardLayout.tsx
  src/main.tsx
  src/pages/customers/[id].tsx
  src/pages/customers/customer.tsx
  src/types/consultation.ts
Labels: Bug

#26 youngseok, hotfix: 프론트엔드 실행 관련 오류 해결 | gitignore에 package-lock.json 추가 #22
  .gitignore
  package-lock.json
  package.json
Labels: Bug

#31 youngseok, feat: 고객 정보 엑셀 양식 다운로드, 업로드 프론트 구현 #13
  src/api/customer.ts
  src/pages/customers/customer.tsx
Labels: Feature

#33 seongeun, feat: 매물, 계약 페이지 구현 #28
  .husky/_/applypatch-msg
  .husky/_/commit-msg
  .husky/_/h
  .husky/_/husky.sh
  .husky/_/post-applypatch
  .husky/_/post-checkout
  .husky/_/post-commit
  .husky/_/post-merge
  .husky/_/post-rewrite
  .husky/_/pre-applypatch
  .husky/_/pre-auto-gc
  .husky/_/pre-commit
  .husky/_/pre-merge-commit
  .husky/_/pre-push
  .husky/_/pre-rebase
  .husky/_/prepare-commit-msg
  src/App.tsx
  src/api/contract.ts
  src/api/property.ts
  src/components/contract/ContractListItem.tsx
  src/components/contract/ContractStatusFilter.tsx
  src/components/contract/ContractTypeFilter.tsx
  src/components/customers/ConsultationForm.tsx
  src/components/customers/ConsultationList.tsx
  src/components/layout/DashboardLayout.tsx
  src/components/property/CustomerDropdown.tsx
  src/components/property/PropertyListItem.tsx
  src/components/property/PropertyTypeFilter.tsx
  src/components/property/PropertyTypeSelector.tsx
  src/pages/contract/ContractDetail.tsx
  src/pages/contract/ContractEdit.tsx
  src/pages/contract/ContractList.tsx
  src/pages/contract/ContractRegistration.tsx
  src/pages/property/PropertyDetail.tsx
  src/pages/property/PropertyEdit.tsx
  src/pages/property/PropertyList.tsx
  src/pages/property/PropertyRegistration.tsx
  src/types/consultation.ts
  src/types/contract.ts
  src/types/property.ts
Labels: Feature

#36 seongeun, feat: 계약, 매물 응답 구조 변경에 따른 pagination type 추가 #28
  src/api/contract.ts
  src/api/property.ts
  src/pages/contract/ContractList.tsx
  src/pages/property/PropertyList.tsx
  src/types/contract.ts
  src/types/pagination.ts
  src/types/property.ts
Labels: Feature

#35 byungchan, feature: 고객 문의 폼 페이지 구현 및 API 연동
  .eslintrc.json
  src/App.tsx
  src/api/client.ts
  src/api/inquiry.ts
  src/components/LogoWithText.tsx
  src/components/inquiry/ErrorMessage.tsx
  src/components/inquiry/FormRenderer.tsx
  src/components/inquiry/QuestionField.tsx
  src/pages/inquiryForm/InquiryCompletePage.tsx
  src/pages/inquiryForm/InquiryFormPage.tsx
  src/pages/inquiryTemplate/InquiryTemplateCreate.tsx
  src/types/inquiry.ts
Labels: Feature

#40 byungchan, fix: 이메일 인증 및 로그아웃 버그 해결
  src/api/auth.ts
  src/context/AuthContext.tsx
  src/hooks/useEmailVerification.ts
  src/pages/auth/SignUp.tsx
Labels: Bug

#44 seongeun, fix: 매물, 계약 목록 조회 시 검색 요청 로직 및 매물 수정 시 고객 드롭다운 수정 #43
  src/api/property.ts
  src/components/property/CustomerDropdown.tsx
  src/components/property/PropertyTypeFilter.tsx
  src/pages/contract/ContractEdit.tsx
  src/pages/contract/ContractList.tsx
  src/pages/contract/ContractRegistration.tsx
  src/pages/property/PropertyEdit.tsx
  src/pages/property/PropertyList.tsx
  src/types/contract.ts
  src/types/property.ts
Labels: Bug

#45 youngseok, feat: 고객 목록 페이지 수정 + 고객 삭제 관련 오류 수정 #41
  src/api/customer.ts
  src/components/customers/CustomerDetailModal.tsx
  src/components/customers/CustomerForm.tsx
  src/components/customers/FilterPanel.tsx
  src/components/customers/PropertyRecommendations.tsx
  src/pages/customers/CustomerManagement.tsx
  src/pages/customers/[id].tsx
  src/pages/customers/customer.tsx
  src/types/customer.ts
Labels: Bug

#47 byungchan, feature: 대시보드 페이지에 통계 데이터 조회 API 연동 #46
  package.json
  src/api/dashboard.ts
  src/components/dashboard/ChartContainer.tsx
  src/components/dashboard/StatCard.tsx
  src/pages/dashboard/Dashboard.tsx
  src/types/dashboard.ts
  src/utils/format.ts
Labels: Feature

#48 youngseok, feat: sms+템플릿 페이지네이션+필터 검색 적용 #41
  src/App.tsx
  src/api/smsApi.ts
  src/components/property/CustomerDropdown.tsx
  src/pages/customers/customer.tsx
  src/pages/sms/send.tsx
  src/pages/sms/sms.tsx
  src/pages/sms/templates/templates.tsx
  src/types/sms.ts
Labels: Bug, Feature

#54 youngseok, fix: 문자+고객 관련 QA 해결 PR #53 #51 #50
  src/components/customers/CustomerDetailModal.tsx
  src/components/customers/CustomerForm.tsx
  src/components/layout/DashboardLayout.tsx
  src/pages/customers/customer.tsx
  src/pages/sms/send.tsx
  src/types/customer.ts
Labels: Bug

#56 seongeun, fix: 백엔드 계약 기간 검증에 따른 코드 추가, 매물이 계약 가능한 상태인지 표시
  src/components/property/PropertyListItem.tsx
  src/pages/contract/ContractEdit.tsx
  src/pages/contract/ContractRegistration.tsx
  src/pages/property/PropertyList.tsx
  src/types/property.ts
Labels: Bug

#59 seongeun, feat: 매물 상태에 따른 필터 추가 #28
  src/api/property.ts
  src/components/property/ActiveStatusFilter.tsx
  src/components/property/ActiveStatusSelector.tsx
  src/pages/property/PropertyList.tsx
  src/types/property.ts
Labels: Feature

#61 대시보드 버그 수정, 계약 등록 및 상담 등록 페이지 모달 추가, 문의 템플릿 관리 페이지 링크 복사 버튼 추가
  src/api/client.ts
  src/api/consultation.ts
  src/api/contract.ts
  src/api/customer.ts
  src/components/customers/CustomerSelectionModal.tsx
  src/components/inquiryTemplate/InquiryTemplateList.tsx
  src/components/property/PropertySelectionModal.tsx
  src/pages/consultation/ConsultationDetailPage.tsx
  src/pages/consultation/ConsultationFormPage.tsx
  src/pages/consultation/ConsultationListPage.tsx
  src/pages/contract/ContractList.tsx
  src/pages/contract/ContractRegistration.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/inquiryTemplate/InquiryTemplateManagement.tsx
  src/types/consultation.ts
  src/types/contract.ts
  src/types/inquiryTemplate.ts
Labels: Feature

#62 byungchan, fix: / 외 경로 접근 시 404 이슈 해결
  src.zip
  vercel.json
Labels: Bug

#63 byungchan, fix: 404 버그 해결
  vercel.json
Labels: Bug

#65 seongeun, fix: canceled 오타 수정 및 지번 주소 type 추가
  src/components/ui/AddressInput.tsx
  src/pages/consultation/ConsultationDetailPage.tsx
  src/pages/consultation/ConsultationFormPage.tsx
  src/pages/consultation/ConsultationListPage.tsx
  src/pages/property/PropertyDetail.tsx
  src/pages/property/PropertyEdit.tsx
  src/pages/property/PropertyRegistration.tsx
  src/types/consultation.ts
  src/types/contract.ts
  src/types/property.ts
Labels: Bug

#68 문의 내역 페이지 구현 및 API 연동, 대시보드 네비게이션 바 깨지는 현상 해결
  src/App.tsx
  src/api/inquiry.ts
  src/components/layout/DashboardLayout.tsx
  src/pages/inquiryManagement/InquiryManagement.tsx
  src/types/inquiry.ts
Labels: Bug, Feature

#71 byungchan, feature: 상담 관리 페이지에서 상담 목록 조회(필터, 검색, 페이지네이션 포함) API 연동 및 수정, 삭제 버튼 구현
  src/api/consultation.ts
  src/pages/consultation/ConsultationListPage.tsx
  src/types/consultation.ts
Labels: Feature

#69 seongeun, fix: console.log 삭제
  src/api/property.ts
  src/components/dashboard/ChartContainer.tsx
  src/components/inquiry/FormRenderer.tsx
  src/components/layout/DashboardLayout.tsx
  src/pages/auth/SignUp.tsx
  src/pages/consultation/ConsultationDetailPage.tsx
  src/pages/contract/ContractDetail.tsx
  src/pages/contract/ContractEdit.tsx
  src/pages/contract/ContractList.tsx
  src/pages/inquiryTemplate/InquiryTemplateManagement.tsx
  src/pages/property/PropertyDetail.tsx
  src/pages/property/PropertyEdit.tsx
  src/pages/property/PropertyList.tsx
  src/pages/sms/templates/templates.tsx
Labels: Bug

#74 byungchan, fix: 상담 등록 및 수정 시 상담일자 제대로 선택 안되는 버그 해결 #73
  src/pages/consultation/ConsultationFormPage.tsx
Labels: Bug

#78 byungchan, feature: 알림 목록 페이지 구현 및 API 연동 #77
  package.json
  src/App.tsx
  src/api/notification.ts
  src/components/dashboard/NotificationItem.tsx
  src/components/layout/DashboardLayout.tsx
  src/components/notification/NotificationBadge.tsx
  src/components/notification/NotificationItem.tsx
  src/components/notification/NotificationList.tsx
  src/components/ui/Button.tsx
  src/context/NotificationContext.tsx
  src/hooks/useOnClickOutside.ts
  src/hooks/useSSE.ts
  src/main.tsx
  src/pages/inquiryManagement/InquiryDetail.tsx
  src/pages/inquiryManagement/InquiryManagement.tsx
  src/pages/notification/NotificationPage.tsx
  src/types/notification.ts
  src/utils/notificationUtil.ts
Labels: Feature

#85 seongeun, feat: 매물 및 계약 페이지 재구현
  src/api/property.ts
  src/components/contract/ContractListItem.tsx
  src/components/property/PropertyDirectionSelector.tsx
  src/components/property/PropertyListItem.tsx
  src/pages/contract/ContractDetail.tsx
  src/pages/contract/ContractEdit.tsx
  src/pages/contract/ContractRegistration.tsx
  src/pages/property/PropertyDetail.tsx
  src/pages/property/PropertyEdit.tsx
  src/pages/property/PropertyList.tsx
  src/pages/property/PropertyRegistration.tsx
  src/types/contract.ts
  src/types/property.ts
Labels: Feature

#92 seongeun, feat: 매물 검색 상세 필터 모달 구현
  src/App.tsx
  src/api/property.ts
  src/components/property/PropertyFilterModal.tsx
  src/components/ui/PriceRangeSlider.tsx
  src/main.tsx
  src/pages/contract/ContractEdit.tsx
  src/pages/contract/ContractRegistration.tsx
  src/pages/property/PropertyDetail.tsx
  src/pages/property/PropertyList.tsx
  src/types/property.ts
Labels: Feature

#90 문의 템플릿 생성 및 목록 페이지 개선
  package.json
  src/api/consultation.ts
  src/api/customer.ts
  src/api/inquiry.ts
  src/api/inquiryTemplate.ts
  src/api/region.ts
  src/components/consultation/CustomerHistory.tsx
  src/components/crawling-property/CrawlingPropertyList.tsx
  src/components/customers/ConsultationForm.tsx
  src/components/customers/ConsultationList.tsx
  src/components/inquiry/FormRenderer.tsx
  src/components/inquiry/QuestionField.tsx
  src/components/inquiryTemplate/InquiryTemplateList.tsx
  src/components/inquiryTemplate/InquiryTemplatePreview.tsx
  src/components/inquiryTemplate/InquiryTemplatePreviewInfo.tsx
  src/components/inquiryTemplate/InquiryTypeSelector.tsx
  src/components/inquiryTemplate/QuestionForm.tsx
  src/components/inquiryTemplate/QuestionPreview.tsx
  src/components/inquiryTemplate/RequiredFieldGenerator.tsx
  src/components/inquiryTemplate/ShareTemplateDialog.tsx
  src/components/inquiryTemplate/SortableItem.tsx
  src/components/region/RegionSelector.tsx
  src/components/ui/Alert.tsx
  src/components/ui/ConfirmDialog.tsx
  src/pages/consultation/ConsultationDetailPage.tsx
  src/pages/consultation/ConsultationFormPage.tsx
  src/pages/consultation/ConsultationListPage.tsx
  src/pages/inquiryForm/InquiryFormPage.tsx
  src/pages/inquiryTemplate/InquiryTemplateCreate.tsx
  src/pages/inquiryTemplate/InquiryTemplateManagement.tsx
  src/types/consultation.ts
  src/types/customer.ts
  src/types/inquiry.ts
  src/types/inquiryTemplate.ts
  src/types/region.ts
  src/utils/defaultInquiryTemplateDescription.ts
  src/utils/questionTemplates.ts
Labels: Feature

#100 customer.tsx 대문자로 변경 + 불필요 코드 제거 고객 가입 시 생년월일 입력하게 수정 + 엑셀 파일 입력 시 오류메세지 모달 생성 + 고객 복구 기능 추가 #94 #86
  src/api/customer.ts
  src/api/smsApi.ts
  src/components/customers/CustomerForm.tsx
  src/components/ui/DatePicker.tsx
  src/main.tsx
  src/pages/customers/CustomerDetailPage.tsx
  src/pages/customers/customer.tsx
  src/pages/property/PropertyEdit.tsx
  src/pages/sms/sms.tsx
  src/types/api.ts
  src/types/customer.ts
  src/types/sms.ts
Labels: Feature

#104 byungchan, feature: 계약 등록/수정 시 매물-고객 선택 로직 개선 및 고객 유효성 검사 강화
  src/components/contract/ContractListItem.tsx
  src/pages/contract/ContractEdit.tsx
  src/pages/contract/ContractRegistration.tsx
  src/types/property.ts
Labels: Feature, Refactor

#102 youngseok, fix: 고객 목록에 삭제된 고객만 선택기능 추가 + 상세 페이지에서 입력값이 없는 필드에 선택 안함 …
  src/api/customer.ts
  src/components/consultation/CustomerHistory.tsx
  src/components/customers/ConsultationForm.tsx
  src/components/customers/CustomerSelectionModal.tsx
  src/pages/consultation/ConsultationFormPage.tsx
  src/pages/contract/ContractEdit.tsx
  src/pages/contract/ContractRegistration.tsx
  src/pages/customers/CustomerDetailPage.tsx
  src/pages/customers/customer.tsx
  src/pages/sms/send.tsx
  src/types/consultation.ts
  src/types/contract.ts
  src/types/customer.ts
  src/types/property.ts
Labels: Feature, Refactor

#108 네비게이션 바 개선
  src/components/layout/DashboardLayout.tsx
Labels: Feature

#109 youngseok, feat: 문자 관련 페이지 고도화
  src/api/smsApi.ts
  src/components/customers/CustomerDetailModal.tsx
  src/components/ui/Select.tsx
  src/pages/customers/CustomerDetailPage.tsx
  src/pages/customers/customer.tsx
  src/pages/sms/send.tsx
  src/pages/sms/sms.tsx
  src/types/property.ts
Labels: Feature, Refactor

#106 seongeun, feat: 계약 가격 표시 변경 및 계약 상태에 따른 수정 버튼 비활성화
  src/components/contract/ContractListItem.tsx
  src/pages/contract/ContractDetail.tsx
  src/pages/contract/ContractEdit.tsx
  src/pages/contract/ContractRegistration.tsx
  src/pages/property/PropertyDetail.tsx
  src/types/contract.ts
Labels: Feature

#111 byungchan, fix: 문의 템플릿 공유 링크 도메인 주소 변경
  src/components/inquiryTemplate/ShareTemplateDialog.tsx
Labels: Feature

#112 byungchan, fix: SSE 연결 도메인 주소 변경
  src/context/NotificationContext.tsx
Labels: Feature

#116 상담 등록 페이지 리팩토링 및 사이드바 버그 해결
  src/components/layout/DashboardLayout.tsx
  src/hooks/useConsultationForm.ts
  src/hooks/useCustomerSelection.tsx
  src/pages/consultation/ConsultationFormPage.tsx
  src/types/consultation.ts
Labels: Feature
